Sheep/Sheep/Models/Sheep.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheep.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SheepEntities : DbContext
    {
        public SheepEntities()
            : base("name=SheepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sheep> Sheep { get; set; }
        public DbSet<Shepherd> Shepherd { get; set; }
    }
}

Sheep/Sheep/Models/Sheep.Designer.cs
// Default code generation is disabled for model 'C:\Users\Ryujin\Documents\Visual Studio 2012\Projects\Sheep\Sheep\Models\Sheep.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

Sheep/Sheep/Models/Sheep.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Sheep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheep
    {
        public int Id { get; set; }

        [StringLength(Int32.MaxValue,MinimumLength = 1)]
        public string Colour { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Shepherd_Id { get; set; }
    
        public virtual Shepherd Shepherd { get; set; }
    }
}

Sheep/Sheep/Models/Shepherd.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Sheep.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Shepherd
    {
        public Shepherd()
        {
            this.Sheep = new HashSet<Sheep>();
        }

        public int Id { get; set; }

        [StringLength(Int32.MaxValue, MinimumLength = 1)]
        public string Name { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Sheep> Sheep { get; set; }
    }
}

Sheep/Sheep/ViewModels/Sheep/SheepPageViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using Sheep.Enums;

namespace Sheep.ViewModels.Sheep
{
    public class SheepPageViewModel : IValidatableObject
    {
        [DisplayName("Xml"), Required(ErrorMessage = "To pole jest wymagane"), AllowHtml]
        public string XmlString { get; set; }

        [DisplayName("AJAX")]
        public bool SendAjax { get; set; }

        public OperationChoosenEnum OperationChoosen { get; set; }

        [DisplayName("Odpowiedź"), AllowHtml]
        public string Response { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {

            var validationResults = new List<ValidationResult>();
            try
            {
                var file = HttpContext.Current.Server.MapPath("/XMLSchema/Sheep.xsd");

                var schemas = new XmlSchemaSet();
                var fileStream = new FileStream(file, FileMode.Open);
                schemas.Add(null, XmlReader.Create(fileStream));
                fileStream.Dispose();

                var doc = XDocument.Parse(XmlString);
                var msg = "";
                doc.Validate(schemas, (o, e) =>
                {
                    msg += e.Message + Environment.NewLine;
                });
                if (!string.IsNullOrWhiteSpace(msg))
                {
                    validationResults.Add(new ValidationResult("Coś się nie zgadza w przesłanym XMLu.... "));
                    validationResults.Add(new ValidationResult(msg));
                }
            }
            catch (Exception e)
            {
                validationResults.Add(new ValidationResult("Coś się nie zgadza w przesłanym XMLu.... "));
                validationResults.Add(new ValidationResult(e.Message));
            }
            return validationResults;
        }

    }
}

Sheep/Sheep/Controllers/Api/ApiController.cs
using System;
using System.Web.Mvc;
using Sheep.ViewModels.Sheep;
using Sheep.ViewService.Interface;

namespace Sheep.Controllers.Api
{
    public class ApiController : Controller
    {
        private readonly ISheepViewService _sheepViewService;

        public ApiController(
            ISheepViewService sheepViewService)
        {
            _sheepViewService = sheepViewService;
        }

        public ActionResult SendRequest()
        {
            var model = new SheepPageViewModel();
            if (!TryUpdateModel(model) || !ModelState.IsValid)
            {
                //zwracać czysty xml czy opakowany?, łatwiej tak bo potem prościej błędy ogarnąć
                //return Content(model.Response, "text/xml");
                return Json(new { Success = false });
            }

            try
            {
                var doc = _sheepViewService.FulfillTask(model);
                model.Response = doc.OuterXml;
            }
            catch (Exception e)
            {
                //return Content(model.Response, "text/xml");
                return Json(new { Success = false });
            }
            //var errors = ModelState.Values.Select(x=>x.Errors);
            //return Content(model.Response, "text/xml");
            return Json(new { Success = true, Data = model.Response });
        }

    }
}

Sheep/Sheep/Controllers/Home/HomeController.cs
using System;
using System.Web.Mvc;
using Sheep.ViewModels.Sheep;
using Sheep.ViewService.Interface;

namespace Sheep.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISheepViewService _sheepViewService;

        public HomeController(
            ISheepViewService sheepViewService)
        {
            _sheepViewService = sheepViewService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new SheepPageViewModel();
            return View(model);
        }

        [HttpPost, ActionName("Index")]
        public ActionResult IndexPost()
        {
            var model = new SheepPageViewModel();
            if (!TryUpdateModel(model) || !ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var doc = _sheepViewService.FulfillTask(model);
                model.Response = doc.OuterXml;
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                return View(model);
            }

            return View(model);
        }

    }
}

Sheep/Sheep/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Sheep.Enums
@model Sheep.ViewModels.Sheep.SheepPageViewModel
@using (Html.BeginForm("Index", "Home"))
{
    @Html.ValidationSummary(true)<br />
    
    @Html.HiddenFor(x => x.OperationChoosen)
    <table>
        <tr>
            <td style="width: 250px">
                @Html.LabelFor(x => x.XmlString)
            </td>
            <td>
                @Html.TextBoxFor(x => x.XmlString)
            </td>
            <td>
                @Html.ValidationMessageFor(x => x.XmlString)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(x => x.SendAjax)
            </td>
            <td>
                @Html.CheckBoxFor(x => x.SendAjax)
            </td>
            <td>
                @Html.ValidationMessageFor(x => x.SendAjax)
            </td>
        </tr>
        <tr>
            <td>Operacje
            </td>
            <td>
                <button type="button" value="@((int)OperationChoosenEnum.DeleteShepherd)">Delete Shepherd</button>
                <br />
                <button type="button" value="@((int)OperationChoosenEnum.CreateShepherdWithSheep)">Create Shepherd With Sheep</button><br />
                <button  type="button" value="@((int)OperationChoosenEnum.ListAllShepherds)">List All Shepherds</button><br />
            </td>
            <td></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(x => x.Response)</td>
            <td colspan="2">
                <div style="width: 400px; min-height: 300px; margin-top: 20px" id="responseDiv">@Model.Response</div>
            </td>
        </tr>
    </table>
}

@section js
{
    <script type="text/javascript">
        $(function () {
            $('button').on('click', function () {
                $('#OperationChoosen').val($(this).val());
                if (!$('#SendAjax').prop('checked')) {
                    $('form').submit();
                } else {
                    $('form').validate();
                    if ($('form').valid()) {
                        $.post('@Url.Action("SendRequest", "Api")', {
                            XmlString: $('#XmlString').val(),
                            OperationChoosen: $('#OperationChoosen').val()
                        }).done(function (data) {
                            if (data.Success == true) {
                                $('#responseDiv').empty();
                                $('#responseDiv').html(data.Data
                                    .replace(/\u003c/g, '&lt;')
                                    .replace(/\u003e/g, '&gt;'));
                            } else {
                                //prościej będzie tak wyświetlić błędy walidacji, jak by trzeba było jsonem to growl chyba najlepszy
                                $('form').submit();
                            }
                        });
                    }
                }
            });
        });
    </script>
}

Sheep/Sheep/Views/Shared/Partial/_Navigation.cshtml
<div id="navigationBar">
    <img src= "@Url.Content("~/Content/Images/sheepla.png")" alt="Sheepla logo" class="logo" />
    <ul>
        <li>
            @Html.ActionLink("Strona głowna", "Index", "Home")
        </li>
    </ul>
</div>

Sheep/Sheep/Views/Shared/_Layout.cshtml
@using SquishIt.Framework
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @MvcHtmlString.Create(
            Bundle.Css()
                .AddDirectory("~/Content/Site")
                .ForceRelease()
                .Render("~/Content/Styles_combined_#.css"))

    @MvcHtmlString.Create(
            Bundle.JavaScript()
                .AddDirectory("~/Scripts/Site")
                .ForceRelease()
                .Render("~/Scripts/Javascript_combined_#.js"))

    @RenderSection("css", false)
</head>

<body>
    @*Można by sobie tutaj renderować partiala z child actionem i robić dymaniczne menu, ale to raczej nie ma przy takim małym projekciku sensu*@
    <div class="bodyContentHolder">
        @Html.Partial("Partial/_Navigation")
        <div class="content">
            @RenderBody()
        </div>
    </div>
</body>
</html>
<footer>
    @RenderSection("js", false)
</footer>